{"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-math/issues/85/comments/40679835.json"}, "html": {"href": "#!/ignitionrobotics/ign-math/issues/85#comment-40679835"}}, "issue": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-math/issues/85.json"}}, "type": "issue", "id": 85, "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-math.json"}, "html": {"href": "#!/ignitionrobotics/ign-math"}, "avatar": {"href": "data/bytebucket.org/ravatar/{18503e50-08ea-4d88-ab99-110fde3c7256}ts=1533305"}}, "type": "repository", "name": "ign-math", "full_name": "ignitionrobotics/ign-math", "uuid": "{18503e50-08ea-4d88-ab99-110fde3c7256}"}, "title": "Frustum edge failure"}, "content": {"raw": "This bug was caused by pull request #193, and has been fixed prior to merging.", "markup": "markdown", "html": "<p>This bug was caused by <a href=\"#!/ignitionrobotics/ign-math/pull-requests/193/fixes-frustum-falsly-reporting-it-contains\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #193</a>, and has been fixed prior to merging.</p>", "type": "rendered"}, "created_on": "2017-10-20T15:18:28.113123+00:00", "user": {"display_name": "Shane Loretz", "uuid": "{656e3311-aad9-45a1-aaf7-b0ee0e84b287}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D"}, "html": {"href": "https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:684383ab-ac95-4859-a350-4a6f41a94a22/c7a1ebf5-cade-4115-9f26-9d3facb776db/128"}}, "nickname": "Shane Loretz", "type": "user", "account_id": "557058:684383ab-ac95-4859-a350-4a6f41a94a22"}, "updated_on": null, "type": "issue_comment", "id": 40679835}