{"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-gazebo/pullrequests/397/comments/123600832.json"}, "html": {"href": "#!/ignitionrobotics/ign-gazebo/pull-requests/397/_/diff#comment-123600832"}}, "parent": {"id": 121763221, "links": {"self": {"href": "data/repositories/ignitionrobotics/ign-gazebo/pullrequests/397/comments/121763221.json"}, "html": {"href": "#!/ignitionrobotics/ign-gazebo/pull-requests/397/_/diff#comment-121763221"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 397, "links": {"self": {"href": "data/repositories/ignitionrobotics/ign-gazebo/pullrequests/397.json"}, "html": {"href": "#!/ignitionrobotics/ign-gazebo/pull-requests/397"}}, "title": "[Blueprint] Logging meshes and materials"}, "content": {"raw": "This is still not working for me :confused: \n\n1. `ign gazebo -r -v 4 fuel.sdf --record-resources --record-path /tmp/log_test`\n1. `rm -rf ~/.ignition/fuel/fuel.ignitionrobotics.org/nate`\n1. `ign gazebo -v 4 --playback /tmp/log_test`\n\nAnd I get:\n\n`[GUI] [Err] [SystemPaths.cc:438] File [file:///home/chapulina/.ignition/fuel/fuel.ignitionrobotics.org/nate/models/my_Backpack/2//meshes/Backpack.dae] resolved to path [/home/c\nhapulina/.ignition/fuel/fuel.ignitionrobotics.org/nate/models/my_Backpack/2//meshes/Backpack.dae] but the path does not exist`\n\nI also noticed that under `/tmp/log_test/home/chapulina/.ignition/fuel/fuel.ignitionrobotics.org/` I have `nate`'s `my_backPack`, but not `chapulina`'s `Gazebo - relative paths`.", "markup": "markdown", "html": "<p>This is still not working for me <img class=\"emoji\" src=\"data/pf-emoji-service--cdn.us-east-1.prod.public.atl-paas.net/standard/551c9814-1d37-4573-819d-afab3afeaf32/48x48/1f615.png\" alt=\"\ud83d\ude15\" title=\":confused:\" data-emoji-short-name=\":confused:\" /> </p>\n<ol>\n<li><code>ign gazebo -r -v 4 fuel.sdf --record-resources --record-path /tmp/log_test</code></li>\n<li><code>rm -rf ~/.ignition/fuel/fuel.ignitionrobotics.org/nate</code></li>\n<li><code>ign gazebo -v 4 --playback /tmp/log_test</code></li>\n</ol>\n<p>And I get:</p>\n<p><code>[GUI] [Err] [SystemPaths.cc:438] File [file:///home/chapulina/.ignition/fuel/fuel.ignitionrobotics.org/nate/models/my_Backpack/2//meshes/Backpack.dae] resolved to path [/home/c\nhapulina/.ignition/fuel/fuel.ignitionrobotics.org/nate/models/my_Backpack/2//meshes/Backpack.dae] but the path does not exist</code></p>\n<p>I also noticed that under <code>/tmp/log_test/home/chapulina/.ignition/fuel/fuel.ignitionrobotics.org/</code> I have <code>nate</code>'s <code>my_backPack</code>, but not <code>chapulina</code>'s <code>Gazebo - relative paths</code>.</p>", "type": "rendered"}, "created_on": "2019-11-06T01:03:42.591129+00:00", "user": {"display_name": "Louise Poubel", "uuid": "{5cfa2075-477b-4ded-bdb9-8d2479544ec4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D"}, "html": {"href": "https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8/7d903d90-c5ea-4182-b7ef-0d467e9e1c74/128"}}, "nickname": "chapulina", "type": "user", "account_id": "557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8"}, "updated_on": "2019-11-06T01:03:42.599882+00:00", "type": "pullrequest_comment", "id": 123600832}