{"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-transport/issues/45/comments/28751327.json"}, "html": {"href": "#!/ignitionrobotics/ign-transport/issues/45#comment-28751327"}}, "issue": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-transport/issues/45.json"}}, "type": "issue", "id": 45, "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-transport.json"}, "html": {"href": "#!/ignitionrobotics/ign-transport"}, "avatar": {"href": "data/bytebucket.org/ravatar/{4249390a-7f55-404b-990d-817ba94cc7ac}ts=1533306"}}, "type": "repository", "name": "ign-transport", "full_name": "ignitionrobotics/ign-transport", "uuid": "{4249390a-7f55-404b-990d-817ba94cc7ac}"}, "title": "Service requests without input parameter"}, "content": {"raw": "**4:** As far as I can tell `WrongEcho()` is not being used by the code at all and you are right about the `EXPECT_FALSE`. I looked where the last commit in the source affecting `WrongEcho( )` (blame function in bitbucket) was [but no luck](#!/ignitionrobotics/ign-transport/commits/e2ff137531a86b10f7e0e51c18ca74ed7bfa72bc)\n\n**5:** You can not open two pull request using the same branches at the same time but once declined you can reopen it in the same way, as usual.\n\n**6:** Reading the code I would say yes to your assumption. Which part is the one you don't understand?\n\n**7:** is this the [`ServiceInfo()`](#!/ignitionrobotics/ign-transport/src/75c1fc2c84b2ad6b2cd8ffa33aff92d22389f52b/include/ignition/transport/Node.hh?at=default&fileviewer=file-view-default#Node.hh-685) that you refer to? I can not find any req in the declaration.", "markup": "markdown", "html": "<p><strong>4:</strong> As far as I can tell <code>WrongEcho()</code> is not being used by the code at all and you are right about the <code>EXPECT_FALSE</code>. I looked where the last commit in the source affecting <code>WrongEcho( )</code> (blame function in bitbucket) was <a data-is-external-link=\"true\" href=\"#!/ignitionrobotics/ign-transport/commits/e2ff137531a86b10f7e0e51c18ca74ed7bfa72bc\" rel=\"nofollow\">but no luck</a></p>\n<p><strong>5:</strong> You can not open two pull request using the same branches at the same time but once declined you can reopen it in the same way, as usual.</p>\n<p><strong>6:</strong> Reading the code I would say yes to your assumption. Which part is the one you don't understand?</p>\n<p><strong>7:</strong> is this the <a data-is-external-link=\"true\" href=\"#!/ignitionrobotics/ign-transport/src/75c1fc2c84b2ad6b2cd8ffa33aff92d22389f52b/include/ignition/transport/Node.hh?at=default&amp;fileviewer=file-view-default#Node.hh-685\" rel=\"nofollow\"><code>ServiceInfo()</code></a> that you refer to? I can not find any req in the declaration.</p>", "type": "rendered"}, "created_on": "2016-06-23T20:20:20.025765+00:00", "user": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "updated_on": null, "type": "issue_comment", "id": 28751327}