{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/ignitionrobotics/ign-transport.json"}, "html": {"href": "#!/ignitionrobotics/ign-transport"}, "avatar": {"href": "data/bytebucket.org/ravatar/{4249390a-7f55-404b-990d-817ba94cc7ac}ts=1533306"}}, "type": "repository", "name": "ign-transport", "full_name": "ignitionrobotics/ign-transport", "uuid": "{4249390a-7f55-404b-990d-817ba94cc7ac}"}, "links": {"attachments": {"href": "data/repositories/ignitionrobotics/ign-transport/issues/18/attachments_page=1.json"}, "self": {"href": "data/repositories/ignitionrobotics/ign-transport/issues/18.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-transport/issues/18/watch"}, "comments": {"href": "data/repositories/ignitionrobotics/ign-transport/issues/18/comments_page=1.json"}, "html": {"href": "#!/ignitionrobotics/ign-transport/issues/18/twoprocsrvcallthousandcalls-test-is"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/ignitionrobotics/ign-transport/issues/18/vote"}}, "reporter": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "title": "twoProcSrvCall.ThousandCalls test is failing from time to time", "component": null, "votes": 0, "watches": 1, "content": {"raw": "Comes from pull request #23. While running the test on Ubuntu Trusty, sometimes is failing with this message:\r\n\r\n```\r\n[ RUN      ] twoProcSrvCall.ThousandCalls\r\n/home/jrivero/code/ignition/ign-transport/test/integration/twoProcessesSrvCallStress.cc:61: Failure\r\nValue of: node.Request(topic, req, timeout, response, result)\r\n  Actual: false\r\nExpected: true\r\n/home/jrivero/code/ignition/ign-transport/test/integration/twoProcessesSrvCallStress.cc:65: Failure\r\nValue of: response.data()\r\n  Actual: 5646\r\nExpected: i\r\nWhich is: 5647\r\n/home/jrivero/code/ignition/ign-transport/test/integration/twoProcessesSrvCallStress.cc:61: Failure\r\nValue of: node.Request(topic, req, timeout, response, result)\r\n  Actual: false\r\nExpected: true\r\n/home/jrivero/code/ignition/ign-transport/test/integration/twoProcessesSrvCallStress.cc:65: Failure\r\nValue of: response.data()\r\n  Actual: 5646\r\nExpected: i\r\nWhich is: 5648\r\n```\r\n", "markup": "markdown", "html": "<p>Comes from <a href=\"#!/ignitionrobotics/ign-transport/pull-requests/23/fix-issue-16\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #23</a>. While running the test on Ubuntu Trusty, sometimes is failing with this message:</p>\n<div class=\"codehilite\"><pre><span></span>[ RUN      ] twoProcSrvCall.ThousandCalls\n/home/jrivero/code/ignition/ign-transport/test/integration/twoProcessesSrvCallStress.cc:61: Failure\nValue of: node.Request(topic, req, timeout, response, result)\n  Actual: false\nExpected: true\n/home/jrivero/code/ignition/ign-transport/test/integration/twoProcessesSrvCallStress.cc:65: Failure\nValue of: response.data()\n  Actual: 5646\nExpected: i\nWhich is: 5647\n/home/jrivero/code/ignition/ign-transport/test/integration/twoProcessesSrvCallStress.cc:61: Failure\nValue of: node.Request(topic, req, timeout, response, result)\n  Actual: false\nExpected: true\n/home/jrivero/code/ignition/ign-transport/test/integration/twoProcessesSrvCallStress.cc:65: Failure\nValue of: response.data()\n  Actual: 5646\nExpected: i\nWhich is: 5648\n</pre></div>", "type": "rendered"}, "assignee": null, "state": "invalid", "version": null, "edited_on": null, "created_on": "2014-10-17T22:49:27.322909+00:00", "milestone": null, "updated_on": "2014-10-28T23:09:17.705126+00:00", "type": "issue", "id": 18}